### PR TITLE
Add kiln and sawmill support

### PR DESCRIPTION
**Pull request by thelegitdolt**

### CODE REVIEW

**Comment by thelegitdolt** [comment]
review???

**Comment by thelegitdolt** [comment]
so anyways. i reused the stonecutter gui for the sawmill and the furnace gui for the kiln. it works quite well in game

**Comment by hatsondogs** [comment]
thanks. i dont even know the features in our own mods so thanks for fixing the oversight!

**Review by hatsondogs — APPROVED** [review]
thanks. i dont even know the features in our own mods so thanks for fixing the oversight!

**Pull request merged**
